registries:
- type: standard
  ref: v4.220.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: aws/aws-cli@2.17.48
- name: cli/cli@v2.56.0
- name: rhysd/actionlint@v1.7.1
- name: simonwhitaker/gibo@v3.0.12
- name: x-motemen/ghq@v1.6.2
- name: gohugoio/hugo@v0.134.2
- name: kubernetes/kubectl@v1.31.0
- name: ahmetb/kubectx@v0.9.5
- name: ahmetb/kubectx/kubens@v0.9.5
- name: shyiko/kubesec@0.9.2
- name: hashicorp/terraform-ls@v0.34.3
- name: aquasecurity/trivy@v0.55.0
- name: terraform-linters/tflint@v0.53.0
- name: stern/stern@v1.30.0
- name: helm/helm@v3.15.4
- name: kubernetes-sigs/kustomize@kustomize/v5.4.3
- name: argoproj/argo-cd@v2.12.3
- name: open-policy-agent/conftest@v0.56.0
- name: open-policy-agent/opa@v1.0.0
- name: google/yamlfmt@v0.17.2
- name: goreleaser/goreleaser@v2.11.2